server:
  http_port: 9001

worker:
  # Multiple of CPU cores to use for processing requests
  concurrency_multiplier: 4

models:
  gemini:
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai"
    env: GENAI_API_KEYS
    codes:
      - "gemini-3.1-pro-preview"
      - "gemini-pro-latest"
      - "gemini-3-pro-preview"
      - "gemini-3-flash-preview"
      - "gemini-flash-latest"
      - "gemini-3.1-flash-lite-preview"
      - "gemini-flash-lite-latest"
      - "gemini-2.5-flash"
      - "gemini-2.5-flash-lite"
      - "gemini-2.0-flash"
      - "gemini-2.0-flash-lite"
      - "gemma-4-31b-it"
      - "gemma-4-26b-a4b-it"

      # Image
      - "gemini-3-pro-image-preview"
      - "gemini-2.5-flash-image"
      - "imagen-4.0-ultra-generate-001"
      - "imagen-4.0-generate-001"
      - "imagen-4.0-fast-generate-001"

  # openrouter:
  #   base_url: "https://openrouter.ai/api/v1"
  #   env: OPENROUTER_API_KEY
  #   codes:
  #     - "z-ai/glm-4.5-air:free"
  #     - "qwen/qwen3-coder:free"
  #     - "tngtech/deepseek-r1t2-chimera:free"
  #     - "x-ai/grok-4.1-fast:free"
  #     - "kwaipilot/kat-coder-pro:free"
  #     - "deepseek/deepseek-r1-0528:free"
  #     - "tngtech/deepseek-r1t-chimera:free"
  #     - "microsoft/mai-ds-r1:free"
  #     - "deepseek/deepseek-chat-v3-0324:free"
  #     - "deepseek/deepseek-r1:free"
